
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hedieh
 */
public class AdminUI extends javax.swing.JFrame {
    InsuranceCompany insuranceCompany;
    Login login;
   
    /**
     * Creates new form AdminUI
     */
    
    public AdminUI(InsuranceCompany company,Login login) throws IOException, ClassNotFoundException, CloneNotSupportedException, PolicyException {
        this.login=login;
        this.insuranceCompany=company;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        usersInfo = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        policiesInfo = new javax.swing.JTextArea();
        usersComboPolicies = new javax.swing.JComboBox<>();
        usersLable5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        usersComboFind = new javax.swing.JComboBox<>();
        findButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        policiesLable = new javax.swing.JLabel();
        policyText = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        thirdPartyPolicy = new javax.swing.JRadioButton();
        comprehensivePolicy = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        policyIDLable = new javax.swing.JLabel();
        policyHolderName = new javax.swing.JTextField();
        policyID = new javax.swing.JTextField();
        numberOfClaimsText = new javax.swing.JTextField();
        carModelText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dayText = new javax.swing.JTextField();
        monthText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        manufacturingYearText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        commentLable = new javax.swing.JLabel();
        commentText = new javax.swing.JTextField();
        driverAgeText = new javax.swing.JTextField();
        levelText = new javax.swing.JTextField();
        driverAgeLable = new javax.swing.JLabel();
        levelLable = new javax.swing.JLabel();
        carTypeComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        usersComboAdd = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        cityNameCheckBox = new javax.swing.JCheckBox();
        carModelCheckBox = new javax.swing.JCheckBox();
        reportButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        policiesInfoTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        usersComboUpdate = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        policiesInfoTable1 = new javax.swing.JTable();
        filterExpiryDateButton1 = new javax.swing.JButton();
        filterExpiryDateButton = new javax.swing.JButton();
        filterCarModelText = new javax.swing.JTextField();
        filterExpiryDateText = new javax.swing.JTextField();
        carModelLable1 = new javax.swing.JLabel();
        ExpiryDateLable1 = new javax.swing.JLabel();
        sortUserName = new javax.swing.JCheckBox();
        usersLable6 = new javax.swing.JLabel();
        usersComboBoxFilter = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        usersInfoTable = new javax.swing.JTable();
        sortName = new javax.swing.JCheckBox();
        sortPremium = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        logOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usersInfo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        usersInfo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        policiesInfo.setColumns(20);
        policiesInfo.setRows(5);
        jScrollPane6.setViewportView(policiesInfo);

        usersComboPolicies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usersComboBoxItemStateChanged(evt);
            }
        });

        usersLable5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usersLable5.setText("Users: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Policies: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersLable5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersComboPolicies, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usersLable5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(usersComboPolicies, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        usersInfo.addTab("Policies", jPanel7);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Users:");

        usersComboFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboBox1ActionPerformed(evt);
            }
        });

        findButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        findButton.setForeground(new java.awt.Color(255, 51, 102));
        findButton.setText("FIND");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        policiesLable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        policiesLable.setText("Policies:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersComboFind, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(policyText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(policiesLable, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(562, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersComboFind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(policiesLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
        );

        usersInfo.addTab("Find Policy", jPanel8);

        buttonGroup1.add(thirdPartyPolicy);
        thirdPartyPolicy.setText("Third Part Policy");
        thirdPartyPolicy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thirdPartyPolicyStateChanged(evt);
            }
        });

        buttonGroup1.add(comprehensivePolicy);
        comprehensivePolicy.setText("Comprehensive Policy");
        comprehensivePolicy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                comprehensivePolicyStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Policy Information");

        jLabel9.setText("Policy Holder Name");

        policyIDLable.setText("Policy ID");

        policyHolderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyHolderNameActionPerformed(evt);
            }
        });

        jLabel10.setText("number of Claims");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Car");

        jLabel12.setText("model ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Expiry Date");

        jLabel14.setText("Day");

        jLabel15.setText("Month");

        jLabel16.setText("Year");

        addButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 0, 102));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Car Type");

        jLabel18.setText("ManufacturingYear ");

        jLabel19.setText("Price");

        commentLable.setText("Comment");

        commentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentTextActionPerformed(evt);
            }
        });

        driverAgeLable.setText("Driver Age");

        levelLable.setText("Level");

        carTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "SED", "LUX", "HATCH", "UTE" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(thirdPartyPolicy)
                            .addGap(44, 44, 44)
                            .addComponent(comprehensivePolicy))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel17))
                                                .addGap(49, 49, 49)))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel18)))
                                        .addComponent(policyIDLable)
                                        .addComponent(jLabel10)))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel16)
                                        .addComponent(commentLable)
                                        .addComponent(driverAgeLable)
                                        .addComponent(levelLable))))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(numberOfClaimsText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(carModelText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(manufacturingYearText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(priceText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(dayText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(monthText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(yearText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(commentText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(driverAgeText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(levelText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(policyHolderName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(policyID, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(carTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(9, 9, 9)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdPartyPolicy)
                    .addComponent(comprehensivePolicy))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyIDLable)
                    .addComponent(policyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(policyHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numberOfClaimsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carModelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(carTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manufacturingYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverAgeLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLable))
                .addGap(39, 39, 39)
                .addComponent(addButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Users:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersComboAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersComboAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usersInfo.addTab("Add Policy", jPanel10);

        reportArea.setColumns(20);
        reportArea.setRows(5);
        jScrollPane8.setViewportView(reportArea);

        cityNameCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cityNameCheckBox.setText("City Name - Total Premiums ");

        carModelCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        carModelCheckBox.setText("Car Model - Total Payments - Average Premium");

        reportButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        reportButton.setForeground(new java.awt.Color(255, 0, 51));
        reportButton.setText("Report");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carModelCheckBox)
                            .addComponent(cityNameCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cityNameCheckBox)
                        .addGap(21, 21, 21)
                        .addComponent(carModelCheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );

        usersInfo.addTab("Report", jPanel1);

        policiesInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(policiesInfoTable);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Users:");

        usersComboUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        usersComboUpdate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usersComboBox4ItemStateChanged(evt);
            }
        });
        usersComboUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboBox4ActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 0, 51));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 0, 51));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(usersComboUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 200, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersComboUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        usersInfo.addTab("Edit/Delete Policy", jPanel11);

        policiesInfoTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(policiesInfoTable1);

        filterExpiryDateButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filterExpiryDateButton1.setText("Filter by Date");
        filterExpiryDateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterExpiryDateButton1ActionPerformed(evt);
            }
        });

        filterExpiryDateButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        filterExpiryDateButton.setForeground(new java.awt.Color(255, 0, 51));
        filterExpiryDateButton.setText("Filter by Date");
        filterExpiryDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterExpiryDateButtonActionPerformed(evt);
            }
        });

        filterCarModelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterCarModelTextKeyReleased(evt);
            }
        });

        carModelLable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        carModelLable1.setText("Car Model");

        ExpiryDateLable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ExpiryDateLable1.setText("Expiry Date");

        sortUserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sortUserName.setText("Sort by UserName");
        sortUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(carModelLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterCarModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(ExpiryDateLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(filterExpiryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(filterExpiryDateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(sortUserName)
                .addGap(66, 66, 66))
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(382, 382, 382)
                    .addComponent(filterExpiryDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(filterCarModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sortUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carModelLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterExpiryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpiryDateLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterExpiryDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(383, 383, 383)
                    .addComponent(filterExpiryDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );

        usersLable6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        usersLable6.setText("Users:");

        usersComboBoxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        usersComboBoxFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usersComboBox5ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersLable6)
                    .addComponent(usersComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(usersLable6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usersComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        usersInfo.addTab("Filter Policy", jPanel13);

        usersInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(usersInfoTable);

        sortName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sortName.setText("Sort by Name");
        sortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortNameActionPerformed(evt);
            }
        });

        sortPremium.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sortPremium.setText("Sort by Premium");
        sortPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPremiumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(sortName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sortPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        usersInfo.addTab("Users Information", jPanel2);

        logOut.setText("Log Out");
        logOut.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logOutStateChanged(evt);
            }
        });
        jMenuBar2.add(logOut);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersInfo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(usersInfo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
          
       fillTable2();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorAdded
        for(User user: insuranceCompany.getUsers().values())
        {
            usersComboPolicies.addItem(user.getName()+":"+user.getUserID());
            usersComboFind.addItem(user.getName()+":"+user.getUserID());
            usersComboAdd.addItem(user.getName()+":"+user.getUserID());
            usersComboUpdate.addItem(user.getName()+":"+user.getUserID());
            usersComboBoxFilter.addItem(user.getName()+":"+user.getUserID());
        }
        fillTable();
        fillTable1();
//        fillTable2();
    }//GEN-LAST:event_jTabbedPane1AncestorAdded

    private void usersComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usersComboBox5ItemStateChanged
        fillTable1();
    }//GEN-LAST:event_usersComboBox5ItemStateChanged

    private void sortUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortUserNameActionPerformed
        fillTable1();
    }//GEN-LAST:event_sortUserNameActionPerformed

    private void filterCarModelTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterCarModelTextKeyReleased
        fillTable1();
    }//GEN-LAST:event_filterCarModelTextKeyReleased

    private void filterExpiryDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterExpiryDateButtonActionPerformed
        fillTable1();
    }//GEN-LAST:event_filterExpiryDateButtonActionPerformed

    private void filterExpiryDateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterExpiryDateButton1ActionPerformed
        //        fillTable1();
    }//GEN-LAST:event_filterExpiryDateButton1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String text=(String)usersComboUpdate.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
        int index=policiesInfoTable.getSelectedRow();
        if(index>=0)
        {
            ArrayList<InsurancePolicy> policy=new ArrayList(user.getPolicies().values());
            UpdateAdminUI updateUI=new UpdateAdminUI(policy.get(index),this);
            updateUI.setVisible(true);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int index=policiesInfoTable.getSelectedRow();
        String text=(String)usersComboUpdate.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
        if(index>=0)
        {
            ArrayList<InsurancePolicy> policy=new ArrayList(user.getPolicies().values());
            user.getPolicies().remove(policy.get(index).getPolicyID());
            fillTable();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void usersComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersComboBox4ActionPerformed

    private void usersComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usersComboBox4ItemStateChanged
        fillTable();
    }//GEN-LAST:event_usersComboBox4ItemStateChanged

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        if(cityNameCheckBox.isSelected())
        {
            ArrayList<String> cities= insuranceCompany.populateDistinctCityNames();
            ArrayList<Double> premiums= insuranceCompany.getTotalPaymentPerCity(cities);
            //HashMap<>String,Double> premiums = insuranceCompany.getTotalPremiumPerCity()
            reportArea.append("----Report cities - Total Premiums----\n");
            for (int i = 0; i < cities.size(); i++)
            {
                reportArea.append("City Name: "+ cities.get(i)+"\nPremiums: "+premiums.get(i)+"\n\n");
            }
        }
        else if(carModelCheckBox.isSelected())
        {
            ArrayList<String> carModels = insuranceCompany.populateDistinctCarModels();
            ArrayList<Integer> counts = insuranceCompany.getTotalCountPerCarModel(carModels);
            ArrayList<Double> payments = insuranceCompany.getTotalPaymentPerCarModel(carModels);
            reportArea.append("----Report Car Model - Total Payments - Average -----\n");
            for (int i = 0; i < counts.size(); i++)
            {
                reportArea.append("Car Model: "+ carModels.get(i) + "\nPayments: " + payments.get(i) + "\nAverage: " + payments.get(i) / (double) counts.get(i)+"\n\n");
            }
        }
    }//GEN-LAST:event_reportButtonActionPerformed

    private void commentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String text=(String)usersComboAdd.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
        String holderName=policyHolderName.getText();
        int id=Integer.parseInt(policyID.getText());
        int numberOfClaims=Integer.parseInt(numberOfClaimsText.getText());
        int day=Integer.parseInt(dayText.getText());
        int month=Integer.parseInt(monthText.getText());
        int year=Integer.parseInt(yearText.getText());
        MyDate date= new MyDate(year,month,day);
        String carModel=carModelText.getText();
        int manufacturingYear=Integer.parseInt(manufacturingYearText.getText());
        int price=Integer.parseInt(priceText.getText());
        CarType carType=CarType.valueOf(carTypeComboBox.getSelectedItem().toString());
        Car car= new Car(carModel,carType,manufacturingYear,price);
        InsurancePolicy policy = null;

        if(thirdPartyPolicy.isSelected()){
            String comment=commentText.getText();
            try {
                policy= new ThirdPartyPolicy(holderName,id,car,numberOfClaims,date,comment);
            } catch (PolicyException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            int driverAge=Integer.parseInt(driverAgeText.getText());
            int level=Integer.parseInt(levelText.getText());
            try {
                policy= new ComprehensivePolicy(holderName,id,car,numberOfClaims,date,driverAge,level);
            } catch (PolicyException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(user.addPolicy(policy))
        {
            JOptionPane.showMessageDialog(this,"Policy Has been added");
            policyID.setText("");
            numberOfClaimsText.setText("");
            dayText.setText("");
            monthText.setText("");
            yearText.setText("");
            carModelText.setText("");
            manufacturingYearText.setText("");
            priceText.setText("");
            commentText.setText("");
            driverAgeText.setText("");
            levelText.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Policy couldn`t add");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void policyHolderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyHolderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policyHolderNameActionPerformed

    private void comprehensivePolicyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_comprehensivePolicyStateChanged
        if (comprehensivePolicy.isSelected())
        {
            driverAgeText.setVisible(true);
            driverAgeLable.setVisible(true);
            levelLable.setVisible(true);
            levelText.setVisible(true);
            commentText.setVisible(false);
            commentLable.setVisible(false);

        }
        else
        {
            commentText.setVisible(true);
            commentLable.setVisible(true);
            driverAgeText.setVisible(false);
            driverAgeLable.setVisible(false);
            levelLable.setVisible(false);
            levelText.setVisible(false);
        }
    }//GEN-LAST:event_comprehensivePolicyStateChanged

    private void thirdPartyPolicyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thirdPartyPolicyStateChanged
        //        if (thirdPartyPolicy.isSelected())
        //        {
            //            driverAgeText.setVisible(false);
            //            driverAgeLable.setVisible(false);
            //            levelLable.setVisible(false);
            //            levelText.setVisible(false);
            //
            //        }
        //        else
        //        {
            //            driverAgeText.setVisible(true);
            //            driverAgeLable.setVisible(true);
            //            levelLable.setVisible(true);
            //            levelText.setVisible(true);
            //        }
    }//GEN-LAST:event_thirdPartyPolicyStateChanged

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        String text=(String)usersComboFind.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
        try
        {
            InsurancePolicy policy= user.findPolicy(Integer.parseInt(policyText.getText()));
            if(policy!=null)
            {
                jTextArea1.append(policy.toString()+"\n");
            }
            else
            {
                jTextArea1.append("Ploicy with ID= "+policyText.getText()+" doesn`t exist.\n");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void usersComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboBox1ActionPerformed
        //         usersComboFind.addItem(user.getName()+" : "+user.getUserID());
    }//GEN-LAST:event_usersComboBox1ActionPerformed

    private void usersComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usersComboBoxItemStateChanged
        String text = (String)usersComboPolicies.getSelectedItem();
        String [] fields =text.split(":");
        //        String userName= fields[0];
        int id = Integer.parseInt(fields[1]);
        policiesInfo.setText(insuranceCompany.findUser(id).toString());
    }//GEN-LAST:event_usersComboBoxItemStateChanged

    private void logOutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logOutStateChanged
//        Login login;
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutStateChanged

    private void sortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameActionPerformed
        fillTable2();
    }//GEN-LAST:event_sortNameActionPerformed

    private void sortPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPremiumActionPerformed
        fillTable2();
    }//GEN-LAST:event_sortPremiumActionPerformed

     public void fillTable()
    {        
        String [] header={"Policy Holder Name","policy ID","Car Model","Car Type","ManufacturingYear","Price","Number of Claims","Expiry Date","Comment","DriverAge","Level","Monthly Payment"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        policiesInfoTable.setModel(model);
        String text=(String)usersComboUpdate.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
        for(InsurancePolicy policy: user.getPolicies().values())
        {
            String[] row=new String[12];
            row[0]=policy.getPolicyHolderName();
            row[1]=policy.getPolicyID()+"";
            row[2]=policy.getCar().getModel();
            row[3]=policy.getCar().getCarType().toString();
            row[4]=policy.getCar().getManufacturingYear()+"";
            row[5]=policy.getCar().getPrice()+"";
            row[6]=policy.getNumberOfClaims()+"";
            row[7]=policy.getExpiryDate().toString();
            if(policy instanceof ThirdPartyPolicy)
            {
                row[8]=((ThirdPartyPolicy)policy).getComment();
                row[9]="NA";
                row[10]="NA";
            }
            else
            {
                row[8]="NA";
                row[9]=((ComprehensivePolicy)policy).getDriverAge()+"";
                row[10]=((ComprehensivePolicy)policy).getLevel()+"";
            }
            String monthlyPayment=String.format("$%2f",policy.calcPremium(10));
            row[11]=monthlyPayment;
            model.addRow(row);
        }
    }
    
    public void fillTable1(){
        String text=(String)usersComboBoxFilter.getSelectedItem();
        String[]fields=text.split(":");
        int ID=Integer.parseInt(fields[1]);
        User user= insuranceCompany.findUser(ID);
         ArrayList<InsurancePolicy>policyCopy=user.shallowCopy();
             try{
                if(!filterCarModelText.getText().isEmpty()) {
                    policyCopy=InsurancePolicy.filterByCarModel(policyCopy, filterCarModelText.getText());
                }
                   else if(!filterExpiryDateText.getText().isEmpty()) {
                         String[]fields1=filterExpiryDateText.getText().split("/");
                         int year=Integer.parseInt(fields1[0]);
                          int month=Integer.parseInt(fields1[1]);
                           int day=Integer.parseInt(fields1[2]);
                           MyDate myDate=new MyDate(year,month,day);
                           policyCopy=InsurancePolicy.filterByExpiryDate(policyCopy, myDate); 
                }
             }
           catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
           }
         if(sortUserName.isSelected())
         {
           Collections.sort(policyCopy);
         }
       
            String [] header={"Policy ID","Policy Holder Name","Car Model","Car Type","Manufacturing Year","Price","Number Of Clims","Expir Date","Driver Age","Level","Comment","Monthly payment"};
            DefaultTableModel model=new DefaultTableModel(header,0);
             policiesInfoTable1.setModel(model);
             for(InsurancePolicy policy1:policyCopy){
             String [] row=new String[12];
             row[0]=policy1.getPolicyID()+"";
             row[1]=policy1.getPolicyHolderName();
             row[2]=policy1.getCarModel();
             row[3]=policy1.car.getCarType().toString();
             row[4]=policy1.car.getManufacturingYear()+"";
             row[5]=policy1.car.getPrice()+"";
             row[6]=policy1.getNumberOfClaims()+"";
             row[7]=policy1.getExpiryDate().toString();
            if(policy1 instanceof ComprehensivePolicy){
             row[8]=((ComprehensivePolicy)policy1).getDriverAge()+"";
             row[9]=((ComprehensivePolicy)policy1).getLevel()+"";
             row[10]="NA";
            }else{
             row[8]="NA";
             row[9]="NA";
             row[10]=((ThirdPartyPolicy)policy1).getComment();
            }
           row[11]=String.format("$%.2f", policy1.calcPremium(10));
           model.addRow(row);
        }
       }
    
    public void fillTable2()
    {        
//         String text=(String)usersComboBoxFilter.getSelectedItem();
//        String[]fields=text.split(":");
//        int ID=Integer.parseInt(fields[1]);
//        User user= insuranceCompany.findUser(ID);
        ArrayList<User>usersCopy=insuranceCompany.shallowCopy();
//        ArrayList<User> usersList = new ArrayList();
        for(User user:insuranceCompany.getUsers().values())
        {
            usersCopy.add(user);
            if(sortName.isSelected())
           {
//              
           }
//        }
          
           if(sortPremium.isSelected())
           {
               
           }
        String [] header={"Name","ID","Password","Street No","Street","Suburb","City","Monthly premiums"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        usersInfoTable.setModel(model);
        for(User user1:insuranceCompany.getUsers().values())
        {
            String[] row=new String[8];
            row[0]=user1.getName();
            row[1]=user1.getUserID()+"";
            row[2]=user1.getUserPassword();
            row[3]=user1.getAddress().getStreetNum()+"";
            row[4]=user1.getAddress().getStreet()+"";
            row[5]=user1.getAddress().getSuburb();
            row[6]=user1.getAddress().getCity();
            String monthlyPayment=String.format("$%2f",user1.calcTotalPremiums(10));
            row[7]=monthlyPayment;
            model.addRow(row);
        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new AdminUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExpiryDateLable1;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox carModelCheckBox;
    private javax.swing.JLabel carModelLable1;
    private javax.swing.JTextField carModelText;
    private javax.swing.JComboBox<String> carTypeComboBox;
    private javax.swing.JCheckBox cityNameCheckBox;
    private javax.swing.JLabel commentLable;
    private javax.swing.JTextField commentText;
    private javax.swing.JRadioButton comprehensivePolicy;
    private javax.swing.JTextField dayText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel driverAgeLable;
    private javax.swing.JTextField driverAgeText;
    private javax.swing.JTextField filterCarModelText;
    private javax.swing.JButton filterExpiryDateButton;
    private javax.swing.JButton filterExpiryDateButton1;
    private javax.swing.JTextField filterExpiryDateText;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel levelLable;
    private javax.swing.JTextField levelText;
    private javax.swing.JMenu logOut;
    private javax.swing.JTextField manufacturingYearText;
    private javax.swing.JTextField monthText;
    private javax.swing.JTextField numberOfClaimsText;
    private javax.swing.JTextArea policiesInfo;
    private javax.swing.JTable policiesInfoTable;
    private javax.swing.JTable policiesInfoTable1;
    private javax.swing.JLabel policiesLable;
    private javax.swing.JTextField policyHolderName;
    private javax.swing.JTextField policyID;
    private javax.swing.JLabel policyIDLable;
    private javax.swing.JTextField policyText;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextArea reportArea;
    private javax.swing.JButton reportButton;
    private javax.swing.JCheckBox sortName;
    private javax.swing.JCheckBox sortPremium;
    private javax.swing.JCheckBox sortUserName;
    private javax.swing.JRadioButton thirdPartyPolicy;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> usersComboAdd;
    private javax.swing.JComboBox<String> usersComboBoxFilter;
    private javax.swing.JComboBox<String> usersComboFind;
    private javax.swing.JComboBox<String> usersComboPolicies;
    private javax.swing.JComboBox<String> usersComboUpdate;
    private javax.swing.JTabbedPane usersInfo;
    private javax.swing.JTable usersInfoTable;
    private javax.swing.JLabel usersLable5;
    private javax.swing.JLabel usersLable6;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
