


import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hedieh
 */
public class UserUI extends javax.swing.JFrame 
{
     User user;
     Login login;
     ArrayList<String>cities;
     
    /**
     * Creates new form UserUI
     */
     
     public  UserUI(User user,Login login,ArrayList<String>cities)
     {
         this.user=user;
         this.login=login;
         this.cities=cities;
         initComponents();
     }
     
//    public UserUI() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        policyGroup = new javax.swing.ButtonGroup();
        policyPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        userID = new javax.swing.JLabel();
        userIDText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        streetNum = new javax.swing.JLabel();
        streetNumText = new javax.swing.JTextField();
        street = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        suburb = new javax.swing.JLabel();
        suburbText = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        citiesComboBox = new javax.swing.JComboBox<>();
        cityText = new javax.swing.JTextField();
        newCity = new javax.swing.JCheckBox();
        changeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        thirdPartyPolicy = new javax.swing.JRadioButton();
        comprehensivePolicy = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        policyIDLable = new javax.swing.JLabel();
        policyHolderName = new javax.swing.JTextField();
        policyID = new javax.swing.JTextField();
        numberOfClaimsText = new javax.swing.JTextField();
        carModelText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dayText = new javax.swing.JTextField();
        monthText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        manufacturingYearText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        commentLable = new javax.swing.JLabel();
        commentText = new javax.swing.JTextField();
        driverAgeText = new javax.swing.JTextField();
        levelText = new javax.swing.JTextField();
        driverAgeLable = new javax.swing.JLabel();
        levelLable = new javax.swing.JLabel();
        carTypeComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        policyInfoArea = new javax.swing.JTextArea();
        PolicyIDLable = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        findPolicy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        policiesInfoTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        policiesInfoTable1 = new javax.swing.JTable();
        filterExpiryDateButton1 = new javax.swing.JButton();
        filterExpiryDateButton = new javax.swing.JButton();
        filterCarModelText = new javax.swing.JTextField();
        filterExpiryDateText = new javax.swing.JTextField();
        carModelLable1 = new javax.swing.JLabel();
        ExpiryDateLable1 = new javax.swing.JLabel();
        sortUserName = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        logOut = new javax.swing.JMenu();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        policyPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                policyPanelStateChanged(evt);
            }
        });

        userID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userID.setText("UserID");

        userIDText.setEditable(false);
        userIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTextActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        name.setText("Name");

        userNameText.setEditable(false);
        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });

        userName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userName.setText("Username");

        password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        password.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Address Information");

        streetNum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        streetNum.setText("Street Number");

        street.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        street.setText("Street");

        suburb.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        suburb.setText("Suburb");

        city.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        city.setText("City");

        citiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sydney", "New York", "London", "Chicago" }));

        newCity.setText("New City");
        newCity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newCityStateChanged(evt);
            }
        });
        newCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCityActionPerformed(evt);
            }
        });

        changeButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        changeButton.setForeground(new java.awt.Color(255, 51, 51));
        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(password)
                                .addGap(18, 18, 18)
                                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(name)
                                            .addComponent(userID))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(userName)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(nameText))
                                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(street)
                                .addComponent(streetNum)
                                .addComponent(suburb)
                                .addComponent(city)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetNumText)
                            .addComponent(streetText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(suburbText)
                            .addComponent(citiesComboBox, 0, 144, Short.MAX_VALUE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(newCity)))
                .addGap(285, 285, 285))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userID))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetNum)
                            .addComponent(streetNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(street))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suburb)
                    .addComponent(suburbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCity)
                    .addComponent(citiesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(changeButton)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        policyPanel.addTab("Edit Personal Data", jPanel1);

        policyGroup.add(thirdPartyPolicy);
        thirdPartyPolicy.setText("Third Part Policy");
        thirdPartyPolicy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thirdPartyPolicyStateChanged(evt);
            }
        });

        policyGroup.add(comprehensivePolicy);
        comprehensivePolicy.setText("Comprehensive Policy");
        comprehensivePolicy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                comprehensivePolicyStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Policy Information");

        jLabel4.setText("Policy Holder Name");

        policyIDLable.setText("Policy ID");

        policyHolderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyHolderNameActionPerformed(evt);
            }
        });

        jLabel8.setText("number of Claims");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Car");

        jLabel10.setText("model ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Expiry Date");

        jLabel12.setText("Day");

        jLabel13.setText("Month");

        jLabel14.setText("Year");

        addButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 0, 102));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 0, 102));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Car Type");

        jLabel18.setText("ManufacturingYear ");

        jLabel19.setText("Price");

        commentLable.setText("Comment");

        commentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentTextActionPerformed(evt);
            }
        });

        driverAgeLable.setText("Driver Age");

        levelLable.setText("Level");

        carTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "SED", "LUX", "HATCH", "UTE" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(thirdPartyPolicy)
                                    .addGap(44, 44, 44)
                                    .addComponent(comprehensivePolicy))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel17))
                                                        .addGap(49, 49, 49)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel18)))
                                                .addComponent(policyIDLable)
                                                .addComponent(jLabel8)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(61, 61, 61)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel14)
                                                .addComponent(commentLable)
                                                .addComponent(driverAgeLable)
                                                .addComponent(levelLable))))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(numberOfClaimsText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(carModelText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(manufacturingYearText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(priceText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(dayText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(monthText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(yearText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(commentText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(driverAgeText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(levelText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(policyHolderName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(policyID, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(carTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(9, 9, 9)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)))
                        .addGap(47, 47, 47)
                        .addComponent(clearButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdPartyPolicy)
                    .addComponent(comprehensivePolicy))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyIDLable)
                    .addComponent(policyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(policyHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numberOfClaimsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carModelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(carTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manufacturingYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(yearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverAgeLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLable))
                .addGap(39, 39, 39)
                .addComponent(addButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        policyPanel.addTab("Add Policies", jPanel2);

        policyInfoArea.setBackground(new java.awt.Color(51, 204, 0));
        policyInfoArea.setColumns(20);
        policyInfoArea.setRows(5);
        jScrollPane1.setViewportView(policyInfoArea);

        PolicyIDLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PolicyIDLable.setText("Policy ID");

        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        findPolicy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        findPolicy.setForeground(new java.awt.Color(255, 0, 51));
        findPolicy.setText("FIND");
        findPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPolicyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(PolicyIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(findPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PolicyIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        policyPanel.addTab("Find a policy", jPanel3);

        policiesInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(policiesInfoTable);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 0, 51));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 0, 51));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        policyPanel.addTab("Policy Information", jPanel4);

        policiesInfoTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(policiesInfoTable1);

        filterExpiryDateButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filterExpiryDateButton1.setText("Filter by Date");
        filterExpiryDateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterExpiryDateButton1ActionPerformed(evt);
            }
        });

        filterExpiryDateButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        filterExpiryDateButton.setForeground(new java.awt.Color(255, 0, 51));
        filterExpiryDateButton.setText("Filter by Date");
        filterExpiryDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterExpiryDateButtonActionPerformed(evt);
            }
        });

        filterCarModelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterCarModelTextKeyReleased(evt);
            }
        });

        carModelLable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carModelLable1.setText("Car Model");

        ExpiryDateLable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExpiryDateLable1.setText("Expiry Date");

        sortUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sortUserName.setText("Sort by UserName");
        sortUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ExpiryDateLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(filterExpiryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(carModelLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(filterCarModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(filterExpiryDateButton)
                .addGap(78, 78, 78)
                .addComponent(sortUserName)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(382, 382, 382)
                    .addComponent(filterExpiryDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterCarModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carModelLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExpiryDateLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterExpiryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterExpiryDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(sortUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(383, 383, 383)
                    .addComponent(filterExpiryDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );

        policyPanel.addTab("Filter Policy", jPanel6);

        logOut.setText("Log Out");
        logOut.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logOutStateChanged(evt);
            }
        });
        jMenuBar1.add(logOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(policyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(policyPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logOutStateChanged
       login.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_logOutStateChanged

    private void policyPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_policyPanelStateChanged
        userIDText.setText(user.getUserID()+"");
        nameText.setText(user.getName());
        userNameText.setText(user.getName());
        passwordText.setText(user.getUserPassword());
        streetNumText.setText(user.getAddress().getStreetNum()+"");
        streetText.setText(user.getAddress().getStreet());
        suburbText.setText(user.getAddress().getSuburb());

        citiesComboBox.setModel(new DefaultComboBoxModel<String>(cities.toArray(new String[0])));
        citiesComboBox.setSelectedItem(user.getCity());
        cityText.setText(user.getCity());
        fillTable();
        fillTable1();
    }//GEN-LAST:event_policyPanelStateChanged

    private void sortUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortUserNameActionPerformed
         fillTable1();
    }//GEN-LAST:event_sortUserNameActionPerformed

    private void filterCarModelTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterCarModelTextKeyReleased
         fillTable1();
    }//GEN-LAST:event_filterCarModelTextKeyReleased

    private void filterExpiryDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterExpiryDateButtonActionPerformed
        fillTable1();
    }//GEN-LAST:event_filterExpiryDateButtonActionPerformed

    private void filterExpiryDateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterExpiryDateButton1ActionPerformed
//        fillTable1();
    }//GEN-LAST:event_filterExpiryDateButton1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int index=policiesInfoTable.getSelectedRow();
        if(index>=0)
        {
            ArrayList<InsurancePolicy> policy=new ArrayList(user.getPolicies().values());
            UpdateUI updateUI=new UpdateUI(policy.get(index),this);
            updateUI.setVisible(true);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int index=policiesInfoTable.getSelectedRow();
        if(index>=0)
        {
            ArrayList<InsurancePolicy> policy=new ArrayList(user.getPolicies().values());
            user.getPolicies().remove(policy.get(index).getPolicyID());
            fillTable();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void findPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPolicyActionPerformed
        try
        {
            InsurancePolicy policy= user.findPolicy(Integer.parseInt(idText.getText()));
            if(policy!=null)
            {
                policyInfoArea.append(policy.toString()+"\n");
            }
            else
            {
                policyInfoArea.append("Ploicy with ID= "+idText.getText()+" doesn`t exist.\n");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_findPolicyActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void commentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentTextActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        policyID.setText("");
        policyHolderName.setText("");
        numberOfClaimsText.setText("");
        dayText.setText("");
        monthText.setText("");
        yearText.setText("");
        carModelText.setText("");
        manufacturingYearText.setText("");
        //        carTypeText.setText("");
        priceText.setText("");
        commentText.setText("");
        driverAgeText.setText("");
        levelText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String holderName=policyHolderName.getText();
        int id=Integer.parseInt(policyID.getText());
        int numberOfClaims=Integer.parseInt(numberOfClaimsText.getText());
        int day=Integer.parseInt(dayText.getText());
        int month=Integer.parseInt(monthText.getText());
        int year=Integer.parseInt(yearText.getText());
        MyDate date= new MyDate(year,month,day);
        String carModel=carModelText.getText();
        int manufacturingYear=Integer.parseInt(manufacturingYearText.getText());
        int price=Integer.parseInt(priceText.getText());
        CarType carType=CarType.valueOf(carTypeComboBox.getSelectedItem().toString());
        Car car= new Car(carModel,carType,manufacturingYear,price);
        InsurancePolicy policy = null;

        if(thirdPartyPolicy.isSelected()){
            String comment=commentText.getText();
            try {
                policy= new ThirdPartyPolicy(holderName,id,car,numberOfClaims,date,comment);
            } catch (PolicyException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            int driverAge=Integer.parseInt(driverAgeText.getText());
            int level=Integer.parseInt(levelText.getText());
            try {
                policy= new ComprehensivePolicy(holderName,id,car,numberOfClaims,date,driverAge,level);
            } catch (PolicyException ex) {
                Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(user.addPolicy(policy))
        {
            JOptionPane.showMessageDialog(this,"Policy Has been added");
            policyID.setText("");
            numberOfClaimsText.setText("");
            dayText.setText("");
            monthText.setText("");
            yearText.setText("");
            carModelText.setText("");
            manufacturingYearText.setText("");
            priceText.setText("");
            commentText.setText("");
            driverAgeText.setText("");
            levelText.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Policy couldn`t add");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void policyHolderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyHolderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policyHolderNameActionPerformed

    private void comprehensivePolicyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_comprehensivePolicyStateChanged
        if (comprehensivePolicy.isSelected())
        {
            driverAgeText.setVisible(true);
            driverAgeLable.setVisible(true);
            levelLable.setVisible(true);
            levelText.setVisible(true);
            commentText.setVisible(false);
            commentLable.setVisible(false);

        }
        else
        {
            commentText.setVisible(true);
            commentLable.setVisible(true);
            driverAgeText.setVisible(false);
            driverAgeLable.setVisible(false);
            levelLable.setVisible(false);
            levelText.setVisible(false);
        }
    }//GEN-LAST:event_comprehensivePolicyStateChanged

    private void thirdPartyPolicyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thirdPartyPolicyStateChanged
        //        if (thirdPartyPolicy.isSelected())
        //        {
            //            driverAgeText.setVisible(false);
            //            driverAgeLable.setVisible(false);
            //            levelLable.setVisible(false);
            //            levelText.setVisible(false);
            //
            //        }
        //        else
        //        {
            //            driverAgeText.setVisible(true);
            //            driverAgeLable.setVisible(true);
            //            levelLable.setVisible(true);
            //            levelText.setVisible(true);
            //        }
    }//GEN-LAST:event_thirdPartyPolicyStateChanged

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        try
        {
            user.setName(nameText.getText());
            user.setUserPassword(passwordText.getText());
            user.getAddress().setStreetNum(Integer.parseInt(streetNumText.getText()));
            user.getAddress().setStreet(streetText.getText());
            user.getAddress().setSuburb(suburbText.getText());
            if(newCity.isSelected())
            {
                user.getAddress().setCity(cityText.getText());
                cities.add(cityText.getText());
                citiesComboBox.setModel(new DefaultComboBoxModel<String>( cities.toArray(new String[0])));
                citiesComboBox.setSelectedItem(cityText.getText());
            }
            else
            {
                user.getAddress().setCity((String)citiesComboBox.getSelectedItem());
                cityText.setText(user.getCity());
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void newCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCityActionPerformed

    }//GEN-LAST:event_newCityActionPerformed

    private void newCityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newCityStateChanged
        if(newCity.isSelected()){
            citiesComboBox.setEnabled(false);
            cityText.setEnabled(true);
        }else{
            citiesComboBox.setEnabled(true);
            cityText.setEnabled(false);
        }
    }//GEN-LAST:event_newCityStateChanged

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        userNameText.setText(user.getName());
    }//GEN-LAST:event_userNameTextActionPerformed

    private void userIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDTextActionPerformed
        userIDText.setText(user.getUserID()+"");
    }//GEN-LAST:event_userIDTextActionPerformed

    
    public void fillTable()
    {
        String [] header={"Policy Holder Name","policy ID","Car Model","Car Type","ManufacturingYear","Price","Number of Claims","Expiry Date","Comment","DriverAge","Level","Monthly Payment"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        policiesInfoTable.setModel(model);
        for(InsurancePolicy policy: user.getPolicies().values())
        {
            String[] row=new String[12];
            row[0]=policy.getPolicyHolderName();
            row[1]=policy.getPolicyID()+"";
            row[2]=policy.getCar().getModel();
            row[3]=policy.getCar().getCarType().toString();
            row[4]=policy.getCar().getManufacturingYear()+"";
            row[5]=policy.getCar().getPrice()+"";
            row[6]=policy.getNumberOfClaims()+"";
            row[7]=policy.getExpiryDate().toString();
            if(policy instanceof ThirdPartyPolicy)
            {
                row[8]=((ThirdPartyPolicy)policy).getComment();
                row[9]="NA";
                row[10]="NA";
            }
            else
            {
                row[8]="NA";
                row[9]=((ComprehensivePolicy)policy).getDriverAge()+"";
                row[10]=((ComprehensivePolicy)policy).getLevel()+"";
            }
            String monthlyPayment=String.format("$%2f",policy.calcPremium(10));
            row[11]=monthlyPayment;
            model.addRow(row);
        }
    }
    
//    public void fillTable1()
//    {
//        ArrayList<InsurancePolicy>policies= user.shallowCopy();
////        for(InsurancePolicy policy: user.getPolicies().values())
////            policies.add(policy);
//        try
//        {
//           if(!filterCarModelText.getText().isEmpty())
//               policies=InsurancePolicy.filterByCarModel(policies, filterCarModelText.getText());
//           if (!filterExpiryDateText.getText().isEmpty())
//           {
//                String [] fields=filterExpiryDateText.getText().split("/");
//                int year= Integer.parseInt(fields[0]);
//                int month= Integer.parseInt(fields[1]);
//                int day= Integer.parseInt(fields[2]);
//                MyDate date= new MyDate(year,month,day);
//                policies=InsurancePolicy.filterByExpiryDate(policies, date);
//           }
//        }
//        catch(Exception e)
//        {
//             JOptionPane.showMessageDialog(this, e);
//        }
//        
//        if(sortUserName.isSelected())
//        {
//            Collections.sort(policies);
//        }
//        String [] header={"Policy Holder Name","policy ID","Car Model","Car Type","ManufacturingYear","Price","Number of Claims","Expiry Date","Comment","DriverAge","Level","Monthly Payment"};
//        DefaultTableModel model=new DefaultTableModel(header,0);
//        policiesInfoTable1.setModel(model);
//        for(InsurancePolicy policy: user.getPolicies().values())
//        {
//            String[] row=new String[12];
//            row[0]=policy.getPolicyHolderName();
//            row[1]=policy.getPolicyID()+"";
//            row[2]=policy.getCar().getModel();
//            row[3]=policy.getCar().getCarType().toString();
//            row[4]=policy.getCar().getManufacturingYear()+"";
//            row[5]=policy.getCar().getPrice()+"";
//            row[6]=policy.getNumberOfClaims()+"";
//            row[7]=policy.getExpiryDate().toString();
//            if(policy instanceof ThirdPartyPolicy)
//            {
//                row[8]=((ThirdPartyPolicy)policy).getComment();
//                row[9]="NA";
//                row[10]="NA";
//            }
//            else
//            {
//                row[8]="NA";
//                row[9]=((ComprehensivePolicy)policy).getDriverAge()+"";
//                row[10]=((ComprehensivePolicy)policy).getLevel()+"";
//            }
//            String monthlyPayment=String.format("$%2f",policy.calcPremium(10));
//            row[11]=monthlyPayment;
//            model.addRow(row);
//        }
//    }
    
       public void fillTable1(){
         ArrayList<InsurancePolicy>policyCopy=user.shallowCopy();
             try{
                if(!filterCarModelText.getText().isEmpty()) {
                    policyCopy=InsurancePolicy.filterByCarModel(policyCopy, filterCarModelText.getText());
                }
                   else if(!filterExpiryDateText.getText().isEmpty()) {
                         String[]fields=filterExpiryDateText.getText().split("/");
                         int year=Integer.parseInt(fields[0]);
                          int month=Integer.parseInt(fields[1]);
                           int day=Integer.parseInt(fields[2]);
                           MyDate myDate=new MyDate(year,month,day);
                           policyCopy=InsurancePolicy.filterByExpiryDate(policyCopy, myDate); 
                }
             }
           catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
           }
         if(sortUserName.isSelected())
         {
           Collections.sort(policyCopy);
         }
           String [] header={"Policy ID","Policy Holder Name","Car Model","Car Type","Manufacturing Year","Price","Number Of Clims","Expir Date","Driver Age","Level","Comment","Monthly "};
            DefaultTableModel model=new DefaultTableModel(header,0);
             policiesInfoTable1.setModel(model);
             for(InsurancePolicy policy1:policyCopy){
             String [] row=new String[12];
             row[0]=policy1.getPolicyID()+"";
             row[1]=policy1.getPolicyHolderName();
             row[2]=policy1.getCarModel();
             row[3]=policy1.car.getCarType().toString();
             row[4]=policy1.car.getManufacturingYear()+"";
             row[5]=policy1.car.getPrice()+"";
             row[6]=policy1.getNumberOfClaims()+"";
             row[7]=policy1.getExpiryDate().toString();
            if(policy1 instanceof ComprehensivePolicy){
             row[8]=((ComprehensivePolicy)policy1).getDriverAge()+"";
             row[9]=((ComprehensivePolicy)policy1).getLevel()+"";
             row[10]="NA";
            }else{
             row[8]="NA";
             row[9]="NA";
             row[10]=((ThirdPartyPolicy)policy1).getComment();
            }
           row[11]=String.format("$%.2f", policy1.calcPremium(10));
           model.addRow(row);
        }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExpiryDateLable1;
    private javax.swing.JLabel PolicyIDLable;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel carModelLable1;
    private javax.swing.JTextField carModelText;
    private javax.swing.JComboBox<String> carTypeComboBox;
    private javax.swing.JButton changeButton;
    private javax.swing.JComboBox<String> citiesComboBox;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityText;
    private javax.swing.JToggleButton clearButton;
    private javax.swing.JLabel commentLable;
    private javax.swing.JTextField commentText;
    private javax.swing.JRadioButton comprehensivePolicy;
    private javax.swing.JTextField dayText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel driverAgeLable;
    private javax.swing.JTextField driverAgeText;
    private javax.swing.JTextField filterCarModelText;
    private javax.swing.JButton filterExpiryDateButton;
    private javax.swing.JButton filterExpiryDateButton1;
    private javax.swing.JTextField filterExpiryDateText;
    private javax.swing.JButton findPolicy;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel levelLable;
    private javax.swing.JTextField levelText;
    private javax.swing.JMenu logOut;
    private javax.swing.JTextField manufacturingYearText;
    private javax.swing.JTextField monthText;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameText;
    private javax.swing.JCheckBox newCity;
    private javax.swing.JTextField numberOfClaimsText;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTable policiesInfoTable;
    private javax.swing.JTable policiesInfoTable1;
    private javax.swing.ButtonGroup policyGroup;
    private javax.swing.JTextField policyHolderName;
    private javax.swing.JTextField policyID;
    private javax.swing.JLabel policyIDLable;
    private javax.swing.JTextArea policyInfoArea;
    private javax.swing.JTabbedPane policyPanel;
    private javax.swing.JTextField priceText;
    private javax.swing.JCheckBox sortUserName;
    private javax.swing.JLabel street;
    private javax.swing.JLabel streetNum;
    private javax.swing.JTextField streetNumText;
    private javax.swing.JTextField streetText;
    private javax.swing.JLabel suburb;
    private javax.swing.JTextField suburbText;
    private javax.swing.JRadioButton thirdPartyPolicy;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userID;
    private javax.swing.JTextField userIDText;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
